name: Setup
description: Setup Foundry, Just, and build contracts

inputs:
  just-version:
    description: "Just version to install"
    required: false
    default: "1.43.1"

runs:
  using: "composite"
  steps:
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Cache Just
      id: just-cache
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/just
        key: just-${{ inputs.just-version }}-${{ runner.os }}

    - name: Install Just
      if: steps.just-cache.outputs.cache-hit != 'true'
      shell: bash
      run: cargo install "just@${{ inputs.just-version }}"
