name: Install Just
description: Install Just

inputs:
  just-tag:
    description: "just version tag"
    required: false
    default: "1.43.1"
outputs:
  cache-path:
    description: "Path to cache"
    value: ${{ steps.cache.outputs.path }}
  cache-key:
    description: "Cache key"
    value: ${{ steps.cache.outputs.key }}

runs:
  using: "composite"
  steps:
    - name: Build cache params
      id: cache
      shell: bash
      run: |
        echo "path=$CACHE_PATH" >> "$GITHUB_OUTPUT"
        echo "$KEY_INPUT" | md5sum | awk '{print $1}' | xargs -I% echo "key=cargobin-%-${RUNNER_OS}" >> "$GITHUB_OUTPUT"
      env:
        CACHE_PATH: |
          ~/.cargo/bin/
        KEY_INPUT: |
          just:${{ inputs.just-tag }}

    - uses: actions/cache@v4
      id: get-cache
      with:
        path: ${{ steps.cache.outputs.path }}
        key: ${{ steps.cache.outputs.key }}

    - name: Install just
      shell: bash
      run: cargo install "just@${{ inputs.just-tag }}"
      if: steps.get-cache.outputs.cache-hit != 'true'
